FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY src ./src

RUN mkdir -p /app/data

ENV NODE_ENV=development
ENV PORT=3001

EXPOSE 3001

CMD ["node", "--watch", "--watch-path=./src", "src/index.js"]